export enum CssTags {
  Main = 'main',
  Header = 'header',
  Section = 'section',
  Button = 'button',
  Form = 'form',
  Input = 'input',
  Div = 'div',
  H1 = 'h1',
  Ul = 'ul',
  Li = 'li',
  Span = 'span',
  P = 'p',
  H3 = 'h3',
  Link = 'a',
  LinkIcon = 'img',
  Image = 'img',
  FieldSet = 'fieldset',
  Label = 'label',
}

export enum CssClasses {
  Main = 'root',
  NotFound = 'not-found',
  Login = 'login-area',
  Password = 'password-area',
  Chat = 'chat-page',
  About = 'about-page',
  Back = 'back-button',
  Header = 'header',
  P = 'info',
  SubHeader = 'subtitle',
  ToUse = 'getting-started-list',
  Item = 'item',
  Span = 'highlighted',
  Link = 'author-link',
  LinkIcon = 'link-to-github',
  Image = 'picture',
  AuthForm = 'auth-form',
  Area = 'area',
  Legend = 'title',
  Label = 'label',
  LoginInput = 'login-input',
  PasswordInput = 'password-input',
  Toggle = 'password-toggle',
  PasswordWrapper = 'password-wrapper',
  LoginButton = 'login-button',
  AboutButton = 'about-button',
  Disable = 'disable',
  ErrorValidation = 'error-validation',
  Invalid = 'invalid',
}
export enum RequestTypes {
  UserLogin = 'USER_LOGIN',
  UserLogout = 'USER_LOGOUT',
  UserActive = 'USER_ACTIVE',
  UserInactive = 'USER_INACTIVE',
  MessageFromUser = 'MSG_FROM_USER',
  MessageSend = 'MSG_SEND',
  MessageRead = 'MSG_READ',
  MessageDelete = 'MSG_DELETE',
  MessageEdit = 'MSG_EDIT',
  UserExternalLogin = 'USER_EXTERNAL_LOGIN',
  UserExternalLogout = 'USER_EXTERNAL_LOGOUT',
  MessageReadFromServer = 'MSG_READED_FROM_SERVER',
  MessageDeleteFromServer = 'MSG_DELETED_FROM_SERVER',
  MessageEditFromServer = 'MSG_EDITED_FROM_SERVER',
  MessageSendedFromServer = 'MSG_SENDED_FROM_SERVER',
  MessageDelivered = 'MSG_DELIVER',
  Error = 'ERROR',
}
