export enum CssTags {
  Main = 'main',
  Header = 'header',
  Section = 'section',
  Button = 'button',
  Form = 'form',
  Input = 'input',
  Div = 'div',
  H1 = 'h1',
  Ul = 'ul',
  Li = 'li',
  Span = 'span',
  P = 'p',
  H3 = 'h3',
  Link = 'a',
  LinkIcon = 'img',
  Image = 'img',
}

export enum CssClasses {
  Main = 'root',
  NotFound = 'not-found',
  Login = 'login-form',
  Chat = 'chat-page',
  About = 'about-page',
  Back = 'back-button',
  Header = 'header',
  P = 'info',
  SubHeader = 'subtitle',
  ToUse = 'getting-started-list',
  Item = 'item',
  Span = 'highlighted',
  Link = 'author-link',
  LinkIcon = 'link-to-github',
  Image = 'picture',
}
